spring:
  sql:
#    init:
#      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LEO_MYSQL_HOST}:3306/kh-blog
    username: admin
    password: ${LEO_MYSQL_PASS}

